apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  AUTH_DB_NAME: auth_db
  AUTH_DB_USER: auth
  AUTH_DB_PASSWORD: auth

  USERS_DB_NAME: users_db
  USERS_DB_USER: users
  USERS_DB_PASSWORD: users

  TICKETS_DB_NAME: tickets_db
  TICKETS_DB_USER: tickets
  TICKETS_DB_PASSWORD: tickets

  AUTH_DATABASE_URL: postgresql://auth:auth@auth-db-service:5432/auth_db
  USERS_DATABASE_URL: postgresql://users:users@users-db-service:5432/users_db
  TICKETS_DATABASE_URL: postgresql://tickets:tickets@tickets-db-service:5432/tickets_db