name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create temporary .env file
        run: |
          cd docker
          cat <<EOF > .env
          AUTH_DB_NAME=${{ secrets.AUTH_DB_NAME }}
          AUTH_DB_USER=${{ secrets.AUTH_DB_USER }}
          AUTH_DB_PASSWORD=${{ secrets.AUTH_DB_PASSWORD }}
          AUTH_DB_PORT=${{ secrets.AUTH_DB_PORT }}
          AUTH_SV_PORT=${{ secrets.AUTH_SV_PORT }}

          USERS_DB_NAME=${{ secrets.USERS_DB_NAME }}
          USERS_DB_USER=${{ secrets.USERS_DB_USER }}
          USERS_DB_PASSWORD=${{ secrets.USERS_DB_PASSWORD }}
          USERS_DB_PORT=${{ secrets.USERS_DB_PORT }}
          USERS_SV_PORT=${{ secrets.USERS_SV_PORT }}

          TICKETS_DB_NAME=${{ secrets.TICKETS_DB_NAME }}
          TICKETS_DB_USER=${{ secrets.TICKETS_DB_USER }}
          TICKETS_DB_PASSWORD=${{ secrets.TICKETS_DB_PASSWORD }}
          TICKETS_DB_PORT=${{ secrets.TICKETS_DB_PORT }}
          TICKETS_SV_PORT=${{ secrets.TICKETS_SV_PORT }}
          EOF

      - name: Build with Docker Compose
        run: |
          cd docker
          docker compose build
